name: Sync

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'yanglbme/actions-toolkit'
    steps:
      - name: Sync To Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:yanglbme/actions-toolkit.git
          destination-repo: git@gitee.com:yanglbme/actions-toolkit.git
